language: node_js
node_js: "stable"

# cache some files for faster builds
cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

# Add global environment
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

# Locate the app folder
before_install:
  - cd app

jobs:
  include:
    - stage: Test
      script:
        - yarn test
    - stage: Deploy Windows & Mac
      os: osx
      osx_image: xcode10.2
      script:
        - yarn release -- --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: Deploy linux
      os: linux
      dist: xenial
      script:
        - yarn release

# only run this script on pull requests and merges into
# the 'master' and 'development' branches
branches:
  only:
    - master
    - development
