language: node_js
node_js: "stable"

# cache some files for faster builds
cache:
  yarn: true
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

# Add global environment
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

# Making the build process parallel: one on mac and one on linux
jobs:
  include:
    - stage: Deploy Windows & Mac
      if: tag IS present
      os: osx
      osx_image: xcode10.2
      before_install:
        - cd app
      script:
        - yarn release --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine

    - stage: Deploy linux
      if: tag IS present
      os: linux
      dist: xenial
      before_install:
        - sudo apt-get install rpm
        - cd app
      # Make apt-get update automatically on every build
      # https://docs.travis-ci.com/user/installing-dependencies/
      addons:
        apt:
          update: true
      script:
        - yarn release

deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  on:
    tags: true
