name: productivity-timer
version: 1.0+git
summary: Beautiful Time Management App for Productivity inspired by Pomodoro Technique.
description: |
  This application is Free and OpenSource and has a lot of useful features that helps boost your productivity. It uses the method called Pomodoro Technique which is proven and tested to increase your overall productiveness.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

parts:
  electron-app:
    source: app/
    plugin: nodejs

    node-engine: 13.6.0
    nodejs-package-manager: yarn

    stage-packages:
      - libgconf2-4
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libxss1
      - libxtst6

    after:
      - desktop-gtk2

    build: node_modules/.bin/electron-builder
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/app
      mv dist/linux-unpacked/* $SNAPCRAFT_PART_INSTALL/app
    prime:
      - -node_modules

apps:
  productivity-timer:
    command: desktop-launch $SNAP/app/productivity-timer
    plugs:
      - desktop
      - desktop-legacy
      - home
      - x11
      - unity7
      - browser-support
      - network
      - gsettings
      - pulseaudio
      - opengl
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
